name: Security

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install pip-audit
      - name: Run pip-audit
        run: pip-audit -r requirements.txt --ignore-vuln CVE-2026-34073 --ignore-vuln CVE-2026-39892 --ignore-vuln CVE-2026-25990 --ignore-vuln CVE-2026-40192 --ignore-vuln CVE-2026-32597 --ignore-vuln CVE-2026-27448 --ignore-vuln CVE-2026-27459 --ignore-vuln CVE-2026-25645 --ignore-vuln GHSA-pjjw-68hj-v9mw --ignore-vuln CVE-2026-22815 --ignore-vuln CVE-2025-67221

  osv-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run OSV-Scanner
        uses: google/osv-scanner-action/osv-scanner-action@v1.9.1
        with:
          scan-args: |-
            --recursive
            ./
